site_name: MovingForth
site_author: Eduardo Furlan
copyright: CC BY 4.0 License
repo_name: efurlanm/ldi
repo_url: http://github.com/efurlanm/ldi/tree/main/movingforth
site_dir: ../docs
site_url: ""
use_directory_urls: false
theme:
    name: material
    font: false
    palette:
        primary: orange
        accent: orange
    features:
        - header.autohide
extra_css:
    - css/extra.css

